services:
  task-manager:
    build:
      context: .
      dockerfile: Dockerfile
    image: java-task-manager:latest
    container_name: task-manager
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:taskmanager;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - redis
    networks:
      - task-manager-network

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - task-manager-network

networks:
  task-manager-network:
    driver: bridge

volumes:
  redis-data: